<!DOCTYPE html> <html lang="pt" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html"> <head> <title>Spring Boot Form</title> <meta charset="UTF-8"/> <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" href="/style.css"/>
</head>
<body>
<div>
    @_TITULO.DO.CABECALHO_@ <br>
    @_TIPO.CEDULA_@ <br> @_NUMERO.CONTRATO_@ <br><strong> VENCIMENTO: @_VENCIMENTO.POR.EXTENSO_@</strong>

</div>
</body>
</html>
